AWS_CLOUD_NAME = 'aws'
AZURE_CLOUD_NAME = 'azure'
GCP_CLOUD_NAME = 'gcp'

PROJECT_GROUP_ID = 'io.github.zubtsov.databricks'
PROJECT_VERSION = '0.0.4'

PROJECT_URL = f'https://github.com/zubtsov/databricks-runtime-dependencies'

ARTIFACT_NAME_PREFIX = 'runtime-bom'
ROOT_ARTIFACT_ID = f'{ARTIFACT_NAME_PREFIX}-root'
LTS_ARTIFACT_ID_SUFFIX = '-lts'
ML_ARTIFACT_ID_SUFFIX = '-ml'
GPU_ARTIFACT_ID_SUFFIX = '-gpu'
CPU_ARTIFACT_ID_SUFFIX = '-cpu'

WINDOWS_OS_FAMILY = 'windows'
MAC_OS_FAMILY = 'mac'
UNIX_OS_FAMILY = 'unix'

X86_64_ARCHITECTURE_MAVEN_NAME = 'x86_64'
ARM_ARCHITECTURE_MAVEN_NAME = 'aarch64'

LINUX_OS_NAME = 'linux'
MAC_OS_NAME = 'osx'
WINDOWS_OS_NAME = 'windows'

WINDOWS_X86_64_INDICATOR = f'{WINDOWS_OS_NAME}-{X86_64_ARCHITECTURE_MAVEN_NAME}'
LINUX_X86_64_INDICATOR = f'{LINUX_OS_NAME}-{X86_64_ARCHITECTURE_MAVEN_NAME}'
MAC_OS_X86_64_INDICATOR = f'{MAC_OS_NAME}-{X86_64_ARCHITECTURE_MAVEN_NAME}'
LINUX_ARM_INDICATOR = f'{LINUX_OS_NAME}-aarch_64'
MAC_OS_ARM_INDICATOR = f'{MAC_OS_NAME}-aarch_64'

COMMON_JINJA_CONTEXT = {
    'PROJECT_GROUP_ID': PROJECT_GROUP_ID,
    'PROJECT_VERSION': PROJECT_VERSION,
    'PROJECT_URL': PROJECT_URL,
    'ROOT_ARTIFACT_ID': ROOT_ARTIFACT_ID,
}
